# Generated by Django 3.2 on 2021-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
