# Generated by Django 3.2 on 2021-04-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_name',
            field=models.ImageField(upload_to='items_images'),
        ),
    ]
