# Generated by Django 3.2 on 2021-04-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_img_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img_name',
            new_name='item_image',
        ),
    ]
