# Generated by Django 3.2 on 2021-04-20 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='u_id',
            field=models.UUIDField(default=uuid.UUID('7bb40f41-3a94-48f7-bed9-cdb1ced4b28d'), editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
