# Generated by Django 3.2 on 2021-04-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210420_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
