# Generated by Django 3.2 on 2021-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_item_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=36)),
                ('order_price_currency', models.CharField(max_length=5)),
                ('order_price', models.FloatField()),
                ('order_name', models.CharField(max_length=200)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('order_address', models.TextField()),
                ('item_id', models.CharField(max_length=36)),
                ('ordered_by', models.CharField(max_length=100)),
                ('order_pending', models.BooleanField()),
            ],
        ),
    ]
