# Generated by Django 3.2 on 2021-05-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_order_item_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_decription',
            new_name='item_description',
        ),
    ]
