# Generated by Django 3.2 on 2021-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_item_decription_item_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(upload_to='items_images'),
        ),
    ]
