# Generated by Django 3.2 on 2021-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_item_item_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('INR', 'USD')], max_length=5),
        ),
    ]
