# Generated by Django 3.2 on 2021-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_item_item_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_video',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5),
        ),
    ]
