# Generated by Django 3.2 on 2021-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210509_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_pending',
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('d', 'Delivered'), ('o', 'On the way')], default='p', max_length=1),
        ),
    ]
